export enum BoxShape {
  SQUARE = 'SQUARE',
  CIRCULAR = 'CIRCULAR',
  ROUNDED = 'ROUNDED',
  CONDITION = 'CONDITION',
  PARALLELOGRAM = 'PARALLELOGRAM',
  REVERSE_PARALLELOGRAM = 'REVERSE_PARALLELOGRAM',
}
